### ISSUE TITLE
Icon suggestion

### ISSUE THREAD

**Issue by rpottsoh** [cmccandless/sitonit#14]
I don't know if you have any say in what icon is used...  If you do, here is a suggestion.

![gi](https://user-images.githubusercontent.com/6978003/40447228-decc6638-5e9f-11e8-8f01-0601cd9eb890.png)

**Comment by cmccandless** [comment]
I love it! Now if only I could do a different background color for pending/passed...

Even so, I've changed it. Thanks!

**Comment by cmccandless** [comment]
Adding for safe-keeping in #15, but the setting that modifies this is outside of the repository.

**Comment by rpottsoh** [comment]
You're welcome.

**Comment by cmccandless** [comment]
@rpottsoh I should've asked before applying this icon: what is the original source for this image? Is it an original work or public domain?

**Comment by rpottsoh** [comment]
found it via a google search.  It is a classic waiting room glyph.  I can
go find it again if you like.

**Comment by cmccandless** [comment]
That would helpful, thanks. Please just paste the original link here for documentation.

**Comment by rpottsoh** [comment]
Link to where I found the symbol:
https://www.symbols.com/symbol/waiting-room
